import { Food } from "@/types";

const data: Food[] = [
  {
    id: "1",
    name: "Cheese Burger",
    restaurant: "Burger House",
    category: "Burgers",
    price: 250,
    rating: 4.5,
    time: 25,
    freeDelivery: true,
    discount: 20,
    veg: false,
    description: "Juicy beef patty with melted cheddar, fresh lettuce, tomatoes, and our signature sauce between toasted brioche buns.",
    image: { uri: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd" },
  },
  {
    id: "2",
    name: "Chicken Pizza",
    restaurant: "Pizza Corner",
    category: "Pizza",
    price: 450,
    rating: 4.7,
    time: 30,
    freeDelivery: false,
    discount: 15,
    veg: false,
    description: "Wood-fired crust topped with tender chicken, bell peppers, onions, mozzarella, and our house-made marinara sauce.",
    image: { uri: "https://images.unsplash.com/photo-1548365328-9f547f2a2a0f" },
  },
  {
    id: "3",
    name: "Veg Momos",
    restaurant: "Momo Station",
    category: "Momos",
    price: 120,
    rating: 4.3,
    time: 15,
    freeDelivery: true,
    discount: 10,
    veg: true,
    description: "Steamed dumplings stuffed with a flavorful mix of finely chopped vegetables, served with spicy tomato chutney.",
    image: { uri: "https://images.unsplash.com/photo-1604908177522-040f8d0a7b3a" },
  },
  {
    id: "4",
    name: "Chicken Biryani",
    restaurant: "Spicy Hut",
    category: "Biryani",
    price: 350,
    rating: 4.8,
    time: 40,
    freeDelivery: false,
    discount: 25,
    veg: false,
    description: "Aromatic basmati rice layered with marinated chicken, caramelized onions, saffron, and traditional spices.",
    image: { uri: "https://images.unsplash.com/photo-1604908554161-2f2f1b1c1c1c" },
  },
  {
    id: "5",
    name: "French Fries",
    restaurant: "Burger House",
    category: "Sides",
    price: 100,
    rating: 4.2,
    time: 10,
    freeDelivery: true,
    discount: 0,
    veg: true,
    description: "Golden crispy fries seasoned with herbs, served with ketchup and mayo dipping sauces.",
    image: { uri: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5" },
  },
  {
    id: "6",
    name: "Grilled Sandwich",
    restaurant: "Cafe Aroma",
    category: "Sandwich",
    price: 180,
    rating: 4.4,
    time: 20,
    freeDelivery: true,
    discount: 5,
    veg: true,
    description: "Toasted whole wheat bread with grilled vegetables, cheese, and pesto spread. A healthy and delicious choice.",
    image: { uri: "https://images.unsplash.com/photo-1550507992-eb63ffee0847" },
  },
  {
    id: "7",
    name: "Double Cheese Burger",
    restaurant: "Burger House",
    category: "Burgers",
    price: 350,
    rating: 4.6,
    time: 30,
    freeDelivery: true,
    discount: 15,
    veg: false,
    description: "Double beef patties with double cheddar, crispy bacon, lettuce, and our secret sauce.",
    image: { uri: "https://images.unsplash.com/photo-1550547660-d9450f859349" },
  },
  {
    id: "8",
    name: "Pepperoni Pizza",
    restaurant: "Pizza Corner",
    category: "Pizza",
    price: 500,
    rating: 4.8,
    time: 35,
    freeDelivery: false,
    discount: 10,
    veg: false,
    description: "Classic pepperoni with mozzarella cheese on our signature thin crust pizza.",
    image: { uri: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38" },
  },
  {
    id: "9",
    name: "Chicken Momos",
    restaurant: "Momo Station",
    category: "Momos",
    price: 150,
    rating: 4.5,
    time: 15,
    freeDelivery: true,
    discount: 0,
    veg: false,
    description: "Steamed dumplings filled with spiced minced chicken, served with tangy dipping sauce.",
    image: { uri: "https://images.unsplash.com/photo-1626132647523-66f5a3800e3e" },
  },
  {
    id: "10",
    name: "Veg Biryani",
    restaurant: "Spicy Hut",
    category: "Biryani",
    price: 280,
    rating: 4.4,
    time: 35,
    freeDelivery: false,
    discount: 20,
    veg: true,
    description: "Fragrant basmati rice cooked with mixed vegetables, saffron, and aromatic spices.",
    image: { uri: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8" },
  },
  {
    id: "11",
    name: "Grilled Chicken",
    restaurant: "Chicken Grill",
    category: "Grill",
    price: 400,
    rating: 4.6,
    time: 30,
    freeDelivery: true,
    discount: 10,
    veg: false,
    description: "Herb-marinated grilled chicken breast served with roasted vegetables and mashed potatoes.",
    image: { uri: "https://images.unsplash.com/photo-1532550907401-a500c9a57435" },
  },
  {
    id: "12",
    name: "Chicken Wings",
    restaurant: "Chicken Grill",
    category: "Grill",
    price: 320,
    rating: 4.5,
    time: 25,
    freeDelivery: true,
    discount: 0,
    veg: false,
    description: "Crispy buffalo wings tossed in spicy sauce, served with blue cheese dip and celery sticks.",
    image: { uri: "https://images.unsplash.com/photo-1608039829572-9b4c0f5c7b4a" },
  },
  {
    id: "13",
    name: "Club Sandwich",
    restaurant: "Cafe Aroma",
    category: "Sandwich",
    price: 220,
    rating: 4.3,
    time: 20,
    freeDelivery: true,
    discount: 0,
    veg: false,
    description: "Triple-decker sandwich with roasted turkey, bacon, lettuce, tomato, and mayo on toasted bread.",
    image: { uri: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af" },
  },
  {
    id: "14",
    name: "BBQ Wings",
    restaurant: "BBQ Nation",
    category: "BBQ",
    price: 380,
    rating: 4.7,
    time: 30,
    freeDelivery: false,
    discount: 15,
    veg: false,
    description: "Smoky barbecue-glazed chicken wings, grilled to perfection and garnished with sesame seeds.",
    image: { uri: "https://images.unsplash.com/photo-1527477396000-e27163b4be8a" },
  },
  {
    id: "15",
    name: "BBQ Platter",
    restaurant: "BBQ Nation",
    category: "BBQ",
    price: 650,
    rating: 4.9,
    time: 45,
    freeDelivery: false,
    discount: 20,
    veg: false,
    description: "Generous platter of grilled ribs, sausages, chicken skewers, and roasted vegetables.",
    image: { uri: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1" },
  },
  {
    id: "16",
    name: "Cold Coffee",
    restaurant: "Cafe Aroma",
    category: "Beverages",
    price: 150,
    rating: 4.2,
    time: 5,
    freeDelivery: true,
    discount: 0,
    veg: true,
    description: "Refreshing iced coffee blended with milk, cream, and a hint of vanilla.",
    image: { uri: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735" },
  },
  {
    id: "17",
    name: "Garlic Bread",
    restaurant: "Pizza Corner",
    category: "Sides",
    price: 130,
    rating: 4.1,
    time: 10,
    freeDelivery: true,
    discount: 0,
    veg: true,
    description: "Toasted baguette slices brushed with garlic butter, herbs, and melted mozzarella.",
    image: { uri: "https://images.unsplash.com/photo-1619535860434-ba1d8fa1252c" },
  },
  {
    id: "18",
    name: "Steam Momos",
    restaurant: "Momo Station",
    category: "Momos",
    price: 130,
    rating: 4.4,
    time: 15,
    freeDelivery: true,
    discount: 0,
    veg: true,
    description: "Classic steamed veg dumplings with a savory filling, served with garlic chutney.",
    image: { uri: "https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5" },
  },
];

export function getFoods(): Food[] {
  return data;
}

export function getFoodById(id: string): Food | undefined {
  return data.find((f) => f.id === id);
}

export function getFoodsByRestaurant(restaurantName: string): Food[] {
  return data.filter((f) => f.restaurant === restaurantName);
}
